---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Red Hat Enterprise Linux Open Lab
    - name: module-02
      label: No really, there are no instructions
tabs:
  - name: terminal
    port: 443
    path: /tty1
